# Generated by Django 2.2.5 on 2019-09-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=200)),
                ('Book_type', models.CharField(max_length=100)),
                ('Book_price', models.IntegerField(default=0)),
            ],
        ),
    ]
