# Generated by Django 2.2.5 on 2019-09-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='book_title',
        ),
        migrations.RenameField(
            model_name='book_title',
            old_name='Book_name',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='book_title',
            old_name='Book_price',
            new_name='book_price',
        ),
        migrations.RenameField(
            model_name='book_title',
            old_name='Book_type',
            new_name='book_type',
        ),
    ]
