# Generated by Django 2.2.5 on 2019-10-07 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('writer_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='board.User')),
            ],
        ),
    ]
